### ISSUE TITLE
CUDA out of memory问题

### ISSUE THREAD

**Issue by LiangYongAI** [Keep-Passion/SESF-Fuse#9]
安装依赖环境，也跑通了main.py，自带的图片也能融合。
但用自有的图片做融合时会出现下面的问题，自有图片大小为10几M，我认为是正常大小，但会出现以下问题。比如改用CPU，比如换更大显存的12G的GPU，试了几个方法都没有成功，有没有什么好的方法可以解决这个问题？
Traceback (most recent call last):
  File "F:/github/SESF-Fuse/main.py", line 28, in <module>
    main(input_dir, output_dir)
  File "F:/github/SESF-Fuse/main.py", line 21, in main
    fused = sesf.fuse(img1, img2)
  File "F:\github\SESF-Fuse\nets\sesf_net.py", line 55, in fuse
    dm = self.model.forward("fuse", img1_tensor, img2_tensor, kernel_radius=self.kernel_radius)
  File "F:\github\SESF-Fuse\nets\sesf_net.py", line 244, in forward
    features_2 = self.features(img2)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1656, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.19 GiB (GPU 0; 8.00 GiB total capacity; 6.10 GiB already allocated; 142.15 MiB free; 13.52 MiB cached)

另外如果是融合自己的数据集，是不是需要用自已的数据集替换COCO重新训练。

**Comment by LiangYongAI** [comment]
@Keep-Passion 能否帮忙看看，谢谢

**Comment by Keep-Passion** [comment]
尝试在推理时增加torch.no_grad(), 我增加后在32GB的显存大小下能跑通3000*4000的图像，这个语句会减少显存占用，我们测试过，发现不用再训练效果也还可以

**Comment by LiangYongAI** [comment]
请问这句话应该加在哪里？能否明示一下，谢谢

**Comment by LiangYongAI** [comment]
我在函数fuse里面把：
 dm = self.model.forward("fuse", img1_tensor, img2_tensor, kernel_radius=self.kernel_radius)
改成：
with torch.no_grad():
      dm = self.model.forward("fuse", img1_tensor, img2_tensor, kernel_radius=self.kernel_radius)
但还是报显存不足，
@Keep-Passion 请问这句话应该加在哪里？能否明示一下

我的图片也大概是3000*4000的大小，但显存只有8GB，是不是说即使用了torch.no_grad()显存也还是不够？

**Comment by Keep-Passion** [comment]
你好，我刚更新了主分支，在sesf_net.py 增加了这个语句，请查看下。
至于如果显存依然不够有四种解决方案：
（1）缩小图像，算出decision map后重新放大回原图尺寸；
（2）改变网络结构，根据你的机器，减少卷积层数量，做网络结构搜索（NAS）；
（3）参考我之前发的论文Overlap-tile策略：https://www.mdpi.com/2073-8994/10/4/107/xml；
（4）追寻最新的网络技术，如Mobilenet,shufflenet系列；推理时考虑半精度、单精度而不是双精度；

**Comment by LiangYongAI** [comment]
@Keep-Passion 按照你说的缩小原图的方法试了下，可以在我自己的图片在推断出结果，效果还可以。
如果对推断时间不敏感，是不是可以用CPU推断，我把代码里面的"cuda:0"全部换成"cpu",但还是报错，这个怎么解？

Traceback (most recent call last):
  File "C:/Users/liangyong/Desktop/image_fusion/SESF-Fuse/main.py", line 34, in <module>
    main(input_dir, output_dir)
  File "C:/Users/liangyong/Desktop/image_fusion/SESF-Fuse/main.py", line 27, in main
    fused = sesf.fuse(img1, img2)
  File "C:\Users\liangyong\Desktop\image_fusion\SESF-Fuse\nets\sesf_net.py", line 53, in fuse
    dm = self.model.forward("fuse", img1_tensor, img2_tensor, kernel_radius=self.kernel_radius)
  File "C:\Users\liangyong\Desktop\image_fusion\SESF-Fuse\nets\sesf_net.py", line 265, in forward
    output = self.fusion_channel_sf(se_cat3_1, se_cat3_2, kernel_radius=kernel_radius)
  File "C:\Users\liangyong\Desktop\image_fusion\SESF-Fuse\nets\sesf_net.py", line 277, in fusion_channel_sf
    .cuda(device).reshape((1, 1, 3, 3)).repeat(c, 1, 1, 1)
RuntimeError: Invalid device, must be cuda device

**Comment by Keep-Passion** [comment]
我当时为了获得最优的性能，所以在特征图上的SF计算也是用GPU并行方法写的，如果你改成了CPU，这里的计算SF也应该是CPU操作，你可以尝试把.cuda(device)去掉

**Comment by Keep-Passion** [comment]
如果感到有帮助，可以点击本项目的新更新的赞助按钮，大大小小都是心意，我得给未出生的孩子攒攒奶粉钱
